{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.env}}-{{ .Values.app.name}}
  namespace: {{ .Values.env}}-{{ .Values.app.name}}
spec:
  hosts:
    - {{ .Values.app.name}}.{{ .Values.env}}.{{ .Values.istio.domain}}
  gateways:
    - {{ .Values.app.name}}-gateway
  http:
    - match:
        - uri:
            prefix: /

      route:
        - destination:
            host: {{ .Values.app.name}}-service
            port:
              number: {{ .Values.service.port}}
{{- end }}
