# This account used to enable R53 access with IAM role
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.global.app.name}}-service
  namespace: {{ .Values.global.env}}-{{ .Values.global.app.name}}
  annotations:
    eks.amazonaws.com/role-arn: {{.Values.global.iam_roles.r53}}
