apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.global.app.name}}-tls-issuer
  namespace: istio-system
spec:
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: {{ .Values.global.app.name}}-tls-issuer
  secretName: {{ .Values.global.app.name}}-tls
  commonName: {{.Values.global.istio.domain}}
  dnsNames:
    - 'nutcorp.net'
    - '*.nutcorp.net'
    - *.{{ .Values.global.env}}.{{.Values.global.istio.domain}}
  usages:
    - server auth
  duration: 2160h0m0s
  renewBefore: 360h0m0s
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always
