apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.global.env}}-{{ .Values.global.app.name}}
  namespace: {{ .Values.global.env}}-{{ .Values.global.app.name}}
spec:
  hosts:
    - {{ .Values.global.app.name}}.{{ .Values.global.env}}.{{ .Values.global.istio.domain}}
  gateways:
    - {{ .Values.global.app.name}}-gateway
  http:
    - match:
        - uri:
            prefix: /

      route:
        - destination:
            host: {{ .Values.global.app.name}}-service
            port:
              number: 3000
